// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvOiKlePBHXfIuBziYuHCOubxbNQNewQI',
    appId: '1:448618578101:web:0b650370bb29e29caa7edc',
    messagingSenderId: '448618578101',
    projectId: 'apporigami-f8b2c',
    authDomain: 'apporigami-f8b2c.firebaseapp.com',
    storageBucket: 'apporigami-f8b2c.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvOiKlePBHXfIuBziYuHCOubxbNQNewQI',
    appId: '1:448618578101:android:0b650370bb29e29caa7edc',
    messagingSenderId: '448618578101',
    projectId: 'apporigami-f8b2c',
    storageBucket: 'apporigami-f8b2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvOiKlePBHXfIuBziYuHCOubxbNQNewQI',
    appId: '1:448618578101:ios:0b650370bb29e29caa7edc',
    messagingSenderId: '448618578101',
    projectId: 'apporigami-f8b2c',
    storageBucket: 'apporigami-f8b2c.appspot.com',
    iosBundleId: 'com.example.apporigami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvOiKlePBHXfIuBziYuHCOubxbNQNewQI',
    appId: '1:448618578101:ios:0b650370bb29e29caa7edc',
    messagingSenderId: '448618578101',
    projectId: 'apporigami-f8b2c',
    storageBucket: 'apporigami-f8b2c.appspot.com',
    iosBundleId: 'com.example.apporigami',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvOiKlePBHXfIuBziYuHCOubxbNQNewQI',
    appId: '1:448618578101:web:0b650370bb29e29caa7edc',
    messagingSenderId: '448618578101',
    projectId: 'apporigami-f8b2c',
    authDomain: 'apporigami-f8b2c.firebaseapp.com',
    storageBucket: 'apporigami-f8b2c.appspot.com',
  );
}
